name: Push Cloud Function deployment
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/push-cloud-function.yml
      - push-arrival-time/**
jobs:
  Deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3

      - name: Authentication
        id: auth
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}

      - name: Deploy function
        id: deploy-function
        uses: google-github-actions/deploy-cloud-functions@v1
        with:
          name: push-arrival-time
          runtime: nodejs18
          entry_point: push
          memory_mb: 128
          source_dir: push-arrival-time
          min_instances: 0
          max_instances: 1
          region: europe-west1